kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-nginx
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/deployments/my-nginx
  generation: 3
  labels:
    run: my-nginx
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 2
  selector:
    matchLabels:
      run: my-nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: my-nginx
    spec:
      containers:
        - name: my-nginx
          image: 'nginx:alpine'
          ports:
          - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m" # 200 milicpu (20%)
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
