kind: Pod
apiVersion: v1
metadata:
  name: my-nginx
  labels:
    app: nginx
    rel: stable
spec:
  containers:
    - name: my-nginx
      image: 'nginx:alpine'
      ports:
      - containerPort: 80
