apiVersion: v1
kind: Pod
metadata:
  name: nginx-alpine-volume
spec:
  containers:
#
  - name: nginx
    image: nginx:alpine
    volumeMounts:
      - name: aws-fs
        mountPath: /usr/aws
        readOnly: false
    resources:
#
  volumes:
  - name: aws-fs
    awsElasticBlockStore:
      volumeID: ...
      fsType: ext4
