apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
  labels:
    app: my-nginx
spec:
  type: LoadBalancer
  selector:
    app: my-nginx
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80